// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package scoped

import (
	"github.com/crclz/go-ioc-example/wire/singleton"
)

// Injectors from wire_stub.go:

func initializeScopedRootComponent(rootComponent *singleton.RootComponent) (*ScopedRootComponent, error) {
	dbConnectionService := FromRootComponentProvideDbConnectionService(rootComponent)
	authenticationService := NewAuthenticationService(dbConnectionService)
	scopedRootComponent := &ScopedRootComponent{
		authenticationService: authenticationService,
	}
	return scopedRootComponent, nil
}
