// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package scoped

import (
	"github.com/crclz/go-ioc-example/wire/singleton"
)

// Injectors from wire_stub.go:

func initializeScopedRootServiceLocator(RootServiceLocator *singleton.RootServiceLocator) (*ScopedRootServiceLocator, error) {
	dbConnectionService := FromRootServiceLocatorProvideDbConnectionService(RootServiceLocator)
	authenticationService := NewAuthenticationService(dbConnectionService)
	scopedRootServiceLocator := &ScopedRootServiceLocator{
		authenticationService: authenticationService,
	}
	return scopedRootServiceLocator, nil
}
