// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package scoped

import (
	"github.com/crclz/go-ioc-example/wire/singleton"
)

// Injectors from wire_stub.go:

func initializeScopedRootDependencyLocator(RootDependencyLocator *singleton.RootDependencyLocator) (*ScopedRootDependencyLocator, error) {
	dbConnectionService := FromRootDependencyLocatorProvideDbConnectionService(RootDependencyLocator)
	authenticationService := NewAuthenticationService(dbConnectionService)
	scopedRootDependencyLocator := &ScopedRootDependencyLocator{
		authenticationService: authenticationService,
	}
	return scopedRootDependencyLocator, nil
}
