// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package singleton

// Injectors from wire_stub.go:

func InitializeRootDependencyLocator() (*RootDependencyLocator, error) {
	dbConnectionService := NewDbConnectionService()
	chatService := NewChatService(dbConnectionService)
	rootDependencyLocator := &RootDependencyLocator{
		ChatService:         chatService,
		DbConnectionService: dbConnectionService,
	}
	return rootDependencyLocator, nil
}
